### ISSUE TITLE
Coletar quantidade de linhas dos arquivos de um diretório

### ISSUE THREAD

**Issue by fanny** [SPLAB-UFCG/Moenda#1]
**Descreva a feature em detalhes**
Deve ser possível coletar a quantidade de linhas de um arquivo

**Necessidade da feature:**
É uma boa métrica para identificar se o programa ou arquivo é grande demais e deveria ser separado em outros módulos

**Como ela pode ser implementada:**

Pode ser usado um regex para coletar a quantidade de linhas

**Contexto adicional:**

**Comment by felipesqra** [comment]
quero fazer essa issue
