### ISSUE TITLE
Consistency in rule names

### ISSUE THREAD

**Issue by fanny** [SPLAB-UFCG/Moenda#28]
## 🚀 Feature

Sometimes our rules starts with a prefix `has` sometimes not as shown below, I would suggest to have consistency among rule names
https://github.com/SPLAB-UFCG/Moenda/blob/25f6f235117417f85ba27fa42f8e94543899b3a8/src/index.js#L6
https://github.com/SPLAB-UFCG/Moenda/blob/25f6f235117417f85ba27fa42f8e94543899b3a8/src/index.js#L68
https://github.com/SPLAB-UFCG/Moenda/blob/25f6f235117417f85ba27fa42f8e94543899b3a8/src/index.js#L159

### Have you read the [Contributing Guidelines on issues](https://github.com/SPLAB-UFCG/Moenda/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yup
## Motivation

Improvement in rules name to make the rules facilitate the rules understanding
## Pitch

You just need to replace the rules name

**Comment by matheusgr** [comment]
Still has tome issues with function names (see first char in uppercase in some rules)
