### ISSUE TITLE
Possibilitar a execução de funções de outros sistemas

### ISSUE THREAD

**Issue by fanny** [SPLAB-UFCG/Moenda#6]
**Descreva a feature em detalhes**

Atualmente o nosso código executa apenas funções próprias, mas seria interessante executar funções fornecidas por outros sistemas.

**Necessidade da feature:**

Uma engine deve ser capaz de executar código externo

**Como ela pode ser implementada:**

um arquivo `.js` ou de outros tipos pode ser fornecido, e pode se obter a(s) função(ões) exportadas e assim, executá-las.

**Contexto adicional:**

**Comment by matheusgr** [comment]
Implementar apenas depois de: 

https://github.com/SPLAB-UFCG/Moenda/issues/12

Como vai funcionar:
- O programa deve ser capaz de executar todas as funções que estiverem em todos os javascripts que começarem com um determinado padrão (`moenda-`, ex.: `moenda-linecounter.js`, `moenda-md.js`)
